### ISSUE TITLE
Function "test_if_scalar_logical" seems to be missing

### ISSUE THREAD

**Issue by precsim** [thrynae/isnetavl#1]
https://github.com/thrynae/isnetavl/blob/1d8ee7a1193a84c0caa537fd5a940f01ab6eea74/isnetavl.m#L30

When looking through the code and trying to understand how it works, it seems that the function "test_if_scalar_logical" called on line 30 (in the case of input to the main function) is missing?

**Comment by thrynae** [comment]
Thank you for pointing out this issue. I will publish an update that includes this function.

For your understanding in the mean time: the first output is true is the input is convertible to a logical and the second output is the converted value. So test_if_scalar_logical('off') with have true as the first output and false as the second, while test_if_scalar_logical("on") will have true for both.

**Comment by thrynae** [comment]
The update has now fixed the issue.
